### ISSUE TITLE
heap-buffer-overflow (READ of size 1) in DecodeBase64Cert()

### ISSUE THREAD

**Issue by geeknik** [mozkeeler/ev-checker#3]
*  git clone
* compile with `-fsanitize=address`
* node server.js
* ./ev-checker -c test000.pem -o 2.16.840.1.114412.2.1 -h localhost:8000 -d "Digicert EV OID"

```
==28750==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61d00000647f at pc 0x00000051b17c bp 0x7fff79c4a030 sp 0x7fff79c4a028
READ of size 1 at 0x61d00000647f thread T0
    #0 0x51b17b in DecodeBase64Cert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /root/ev-checker/ev-checker.cpp:49:7
    #1 0x51b7a8 in ReadCertsFromFile(char const*) /root/ev-checker/ev-checker.cpp:99:31
    #2 0x51f2d4 in main /root/ev-checker/ev-checker.cpp:230:28
    #3 0x7f3b8ea33b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #4 0x41cb89 in _start (/root/ev-checker/ev-checker+0x41cb89)

0x61d00000647f is located 1 bytes to the left of 2049-byte region [0x61d000006480,0x61d000006c81)
allocated by thread T0 here:
    #0 0x4f3c12 in operator new(unsigned long) /b/swarming/w/ir/kitchen-workdir/src/third_party/llvm/compiler-rt/lib/asan/asan_new_delete.cc:106:3
    #1 0x7f3b8fb0cdbe in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x128dbe)

SUMMARY: AddressSanitizer: heap-buffer-overflow /root/ev-checker/ev-checker.cpp:49:7 in DecodeBase64Cert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
```

[test000.pem.gz](https://github.com/mozkeeler/ev-checker/files/2263664/test000.pem.gz)

**Comment by mozkeeler** [comment]
Thanks!
